#include "test_libft.h"

int main(void)
{
    printf("Testing libft functions\n");
    printf("\nTesting ft_strlen\n");
    test_ft_strlen();
    printf("\nTesting ft_memset\n");
    test_ft_memset();
    printf("\nTesting ft_bzero\n");
    test_ft_bzero();
    printf("\nTesting ft_memcpy\n");
    test_ft_memcpy();
    printf("\nTesting ft_memmove\n");
    test_ft_memmove();
    printf("\nTesting ft_strlcpy\n");
    test_ft_strlcpy();
    printf("\nTesting ft_strlcat\n");
    test_ft_strlcat();
    printf("\nTesting ft_strchr\n");
    test_ft_strchr();
    printf("\nTesting ft_strrchr\n");
    test_ft_strrchr();
    printf("\nTesting ft_strncmp\n");
    test_ft_strncmp();
    printf("\nTesting ft_memchr\n");
    test_ft_memchr();
    printf("\nTesting ft_memcmp\n");
    test_ft_memcmp();
    printf("\nTesting ft_strnstr\n");
    test_ft_strnstr();
    printf("\nTesting ft_atoi\n");
    test_ft_atoi();
    printf("\nTesting ft_calloc\n");
    test_ft_calloc();
    printf("\nTesting ft_strdup\n");
    test_ft_strdup();
    printf("\nTesting ft_substr\n");
    test_ft_substr();
    printf("\nTesting ft_strjoin\n");
    test_ft_strjoin();
    printf("\nTesting ft_strtrim\n");
    test_ft_strtrim();
    printf("\nTesting ft_split\n");
    test_ft_split();
    printf("\nTesting ft_itoa\n");
    test_ft_itoa();
    printf("\nTesting ft_strmapi\n");
    test_ft_strmapi();
    printf("\nTesting ft_striteri\n");
    test_ft_striteri();
    printf("\nTesting ft_putchar_fd\n");
    test_ft_putchar_fd();
    printf("\nTesting ft_putstr_fd\n");
    test_ft_putstr_fd();
    printf("\nTesting ft_putendl_fd\n");
    test_ft_putendl_fd();
    printf("\nTesting ft_putnbr_fd\n");
    test_ft_putnbr_fd();
    printf("\nTesting ft_lstnew\n");
    test_ft_lstnew();
    printf("\nTesting ft_lstadd_front\n");
    test_ft_lstadd_front();
    printf("\nTesting ft_lstsize\n");
    test_ft_lstsize();
    printf("\nTesting ft_lstlast\n");
    test_ft_lstlast();
    printf("\nTesting ft_lstadd_back\n");
    test_ft_lstadd_back();
    printf("\nTesting ft_lsdelone\n");
    test_ft_lstdelone();
    printf("\nTesting ft_lstclear\n");
    test_ft_lstclear();
    printf("\nTesting ft_lstiter\n");
    test_ft_lstiter();
    printf("\nTesting ft_lstmap\n");
    test_ft_lstmap();
    printf("\nFinished testing libft functions\n");
    return (0);
}